//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 04:46:40 PM EST 
//


package au.com.sixtree.mule.modules.xero.xsd;

import java.math.BigDecimal;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.com.sixtree.mule.modules.xero.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvoiceFullyPaidOnDate_QNAME = new QName("", "FullyPaidOnDate");
    private final static QName _InvoiceUpdatedDateUTC_QNAME = new QName("", "UpdatedDateUTC");
    private final static QName _Items_QNAME = new QName("", "Items");
    private final static QName _Accounts_QNAME = new QName("", "Accounts");
    private final static QName _Users_QNAME = new QName("", "Users");
    private final static QName _BankTransactions_QNAME = new QName("", "BankTransactions");
    private final static QName _TrackingCategories_QNAME = new QName("", "TrackingCategories");
    private final static QName _Response_QNAME = new QName("", "Response");
    private final static QName _Employees_QNAME = new QName("", "Employees");
    private final static QName _BrandingThemes_QNAME = new QName("", "BrandingThemes");
    private final static QName _Setup_QNAME = new QName("", "Setup");
    private final static QName _TaxRates_QNAME = new QName("", "TaxRates");
    private final static QName _Attachments_QNAME = new QName("", "Attachments");
    private final static QName _Manualjournals_QNAME = new QName("", "Manualjournals");
    private final static QName _Currencies_QNAME = new QName("", "Currencies");
    private final static QName _CreditNotes_QNAME = new QName("", "CreditNotes");
    private final static QName _Invoices_QNAME = new QName("", "Invoices");
    private final static QName _Organisations_QNAME = new QName("", "Organisations");
    private final static QName _Contacts_QNAME = new QName("", "Contacts");
    private final static QName _Journals_QNAME = new QName("", "Journals");
    private final static QName _ExpenseClaims_QNAME = new QName("", "ExpenseClaims");
    private final static QName _LineItems_QNAME = new QName("", "LineItems");
    private final static QName _Receipts_QNAME = new QName("", "Receipts");
    private final static QName _CreditNoteSubTotal_QNAME = new QName("", "SubTotal");
    private final static QName _CreditNoteDueDate_QNAME = new QName("", "DueDate");
    private final static QName _CreditNoteTotalTax_QNAME = new QName("", "TotalTax");
    private final static QName _CreditNoteLineAmountTypes_QNAME = new QName("", "LineAmountTypes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.com.sixtree.mule.modules.xero.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfItem }
     * 
     */
    public ArrayOfItem createArrayOfItem() {
        return new ArrayOfItem();
    }

    /**
     * Create an instance of {@link ArrayOfAccount }
     * 
     */
    public ArrayOfAccount createArrayOfAccount() {
        return new ArrayOfAccount();
    }

    /**
     * Create an instance of {@link ArrayOfUser }
     * 
     */
    public ArrayOfUser createArrayOfUser() {
        return new ArrayOfUser();
    }

    /**
     * Create an instance of {@link ArrayOfBankTransaction }
     * 
     */
    public ArrayOfBankTransaction createArrayOfBankTransaction() {
        return new ArrayOfBankTransaction();
    }

    /**
     * Create an instance of {@link ArrayOfTrackingCategory }
     * 
     */
    public ArrayOfTrackingCategory createArrayOfTrackingCategory() {
        return new ArrayOfTrackingCategory();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link ArrayOfEmployee }
     * 
     */
    public ArrayOfEmployee createArrayOfEmployee() {
        return new ArrayOfEmployee();
    }

    /**
     * Create an instance of {@link ArrayOfBrandingTheme }
     * 
     */
    public ArrayOfBrandingTheme createArrayOfBrandingTheme() {
        return new ArrayOfBrandingTheme();
    }

    /**
     * Create an instance of {@link SetupType }
     * 
     */
    public SetupType createSetupType() {
        return new SetupType();
    }

    /**
     * Create an instance of {@link ArrayOfTaxRate }
     * 
     */
    public ArrayOfTaxRate createArrayOfTaxRate() {
        return new ArrayOfTaxRate();
    }

    /**
     * Create an instance of {@link ArrayOfAttachment }
     * 
     */
    public ArrayOfAttachment createArrayOfAttachment() {
        return new ArrayOfAttachment();
    }

    /**
     * Create an instance of {@link ArrayOfManualJournal }
     * 
     */
    public ArrayOfManualJournal createArrayOfManualJournal() {
        return new ArrayOfManualJournal();
    }

    /**
     * Create an instance of {@link ArrayOfCurrency }
     * 
     */
    public ArrayOfCurrency createArrayOfCurrency() {
        return new ArrayOfCurrency();
    }

    /**
     * Create an instance of {@link ArrayOfCreditNote }
     * 
     */
    public ArrayOfCreditNote createArrayOfCreditNote() {
        return new ArrayOfCreditNote();
    }

    /**
     * Create an instance of {@link ArrayOfInvoice }
     * 
     */
    public ArrayOfInvoice createArrayOfInvoice() {
        return new ArrayOfInvoice();
    }

    /**
     * Create an instance of {@link ArrayOfOrganisation }
     * 
     */
    public ArrayOfOrganisation createArrayOfOrganisation() {
        return new ArrayOfOrganisation();
    }

    /**
     * Create an instance of {@link ArrayOfJournal }
     * 
     */
    public ArrayOfJournal createArrayOfJournal() {
        return new ArrayOfJournal();
    }

    /**
     * Create an instance of {@link ArrayOfContact }
     * 
     */
    public ArrayOfContact createArrayOfContact() {
        return new ArrayOfContact();
    }

    /**
     * Create an instance of {@link ArrayOfExpenseClaim }
     * 
     */
    public ArrayOfExpenseClaim createArrayOfExpenseClaim() {
        return new ArrayOfExpenseClaim();
    }

    /**
     * Create an instance of {@link ArrayOfLineItem }
     * 
     */
    public ArrayOfLineItem createArrayOfLineItem() {
        return new ArrayOfLineItem();
    }

    /**
     * Create an instance of {@link ArrayOfReceipt }
     * 
     */
    public ArrayOfReceipt createArrayOfReceipt() {
        return new ArrayOfReceipt();
    }

    /**
     * Create an instance of {@link ArrayOfAddress }
     * 
     */
    public ArrayOfAddress createArrayOfAddress() {
        return new ArrayOfAddress();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link ReportCellAttribute }
     * 
     */
    public ReportCellAttribute createReportCellAttribute() {
        return new ReportCellAttribute();
    }

    /**
     * Create an instance of {@link ReportRows }
     * 
     */
    public ReportRows createReportRows() {
        return new ReportRows();
    }

    /**
     * Create an instance of {@link ArrayOfPhone }
     * 
     */
    public ArrayOfPhone createArrayOfPhone() {
        return new ArrayOfPhone();
    }

    /**
     * Create an instance of {@link TrackingCategoryOption }
     * 
     */
    public TrackingCategoryOption createTrackingCategoryOption() {
        return new TrackingCategoryOption();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link ArrayOfWarning }
     * 
     */
    public ArrayOfWarning createArrayOfWarning() {
        return new ArrayOfWarning();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link ArrayOfContactGroup }
     * 
     */
    public ArrayOfContactGroup createArrayOfContactGroup() {
        return new ArrayOfContactGroup();
    }

    /**
     * Create an instance of {@link BrandingTheme }
     * 
     */
    public BrandingTheme createBrandingTheme() {
        return new BrandingTheme();
    }

    /**
     * Create an instance of {@link TrackingCategory }
     * 
     */
    public TrackingCategory createTrackingCategory() {
        return new TrackingCategory();
    }

    /**
     * Create an instance of {@link ArrayOfJournalLine }
     * 
     */
    public ArrayOfJournalLine createArrayOfJournalLine() {
        return new ArrayOfJournalLine();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link ArrayOfReport }
     * 
     */
    public ArrayOfReport createArrayOfReport() {
        return new ArrayOfReport();
    }

    /**
     * Create an instance of {@link ArrayOfTrackingCategoryOption }
     * 
     */
    public ArrayOfTrackingCategoryOption createArrayOfTrackingCategoryOption() {
        return new ArrayOfTrackingCategoryOption();
    }

    /**
     * Create an instance of {@link ManualJournalLine }
     * 
     */
    public ManualJournalLine createManualJournalLine() {
        return new ManualJournalLine();
    }

    /**
     * Create an instance of {@link ReportFields }
     * 
     */
    public ReportFields createReportFields() {
        return new ReportFields();
    }

    /**
     * Create an instance of {@link ArrayOfValidationError }
     * 
     */
    public ArrayOfValidationError createArrayOfValidationError() {
        return new ArrayOfValidationError();
    }

    /**
     * Create an instance of {@link ReportCells }
     * 
     */
    public ReportCells createReportCells() {
        return new ReportCells();
    }

    /**
     * Create an instance of {@link ReportRow }
     * 
     */
    public ReportRow createReportRow() {
        return new ReportRow();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link ReportCell }
     * 
     */
    public ReportCell createReportCell() {
        return new ReportCell();
    }

    /**
     * Create an instance of {@link TaxRate }
     * 
     */
    public TaxRate createTaxRate() {
        return new TaxRate();
    }

    /**
     * Create an instance of {@link ApiException }
     * 
     */
    public ApiException createApiException() {
        return new ApiException();
    }

    /**
     * Create an instance of {@link ReportAttribute }
     * 
     */
    public ReportAttribute createReportAttribute() {
        return new ReportAttribute();
    }

    /**
     * Create an instance of {@link ReportAttributes }
     * 
     */
    public ReportAttributes createReportAttributes() {
        return new ReportAttributes();
    }

    /**
     * Create an instance of {@link Receipt }
     * 
     */
    public Receipt createReceipt() {
        return new Receipt();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link ReportCellAttributes }
     * 
     */
    public ReportCellAttributes createReportCellAttributes() {
        return new ReportCellAttributes();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link ContactGroup }
     * 
     */
    public ContactGroup createContactGroup() {
        return new ContactGroup();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ReportField }
     * 
     */
    public ReportField createReportField() {
        return new ReportField();
    }

    /**
     * Create an instance of {@link JournalLine }
     * 
     */
    public JournalLine createJournalLine() {
        return new JournalLine();
    }

    /**
     * Create an instance of {@link CreditNote }
     * 
     */
    public CreditNote createCreditNote() {
        return new CreditNote();
    }

    /**
     * Create an instance of {@link ExpenseClaim }
     * 
     */
    public ExpenseClaim createExpenseClaim() {
        return new ExpenseClaim();
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link ArrayOfManualJournalLine }
     * 
     */
    public ArrayOfManualJournalLine createArrayOfManualJournalLine() {
        return new ArrayOfManualJournalLine();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link ItemPriceDetails }
     * 
     */
    public ItemPriceDetails createItemPriceDetails() {
        return new ItemPriceDetails();
    }

    /**
     * Create an instance of {@link ManualJournal }
     * 
     */
    public ManualJournal createManualJournal() {
        return new ManualJournal();
    }

    /**
     * Create an instance of {@link BankTransaction }
     * 
     */
    public BankTransaction createBankTransaction() {
        return new BankTransaction();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Hyperlink }
     * 
     */
    public Hyperlink createHyperlink() {
        return new Hyperlink();
    }

    /**
     * Create an instance of {@link ArrayOfPayment }
     * 
     */
    public ArrayOfPayment createArrayOfPayment() {
        return new ArrayOfPayment();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link ReportTitles }
     * 
     */
    public ReportTitles createReportTitles() {
        return new ReportTitles();
    }

    /**
     * Create an instance of {@link ValidationError }
     * 
     */
    public ValidationError createValidationError() {
        return new ValidationError();
    }

    /**
     * Create an instance of {@link LineItem }
     * 
     */
    public LineItem createLineItem() {
        return new LineItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FullyPaidOnDate", scope = Invoice.class)
    public JAXBElement<XMLGregorianCalendar> createInvoiceFullyPaidOnDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_InvoiceFullyPaidOnDate_QNAME, XMLGregorianCalendar.class, Invoice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdatedDateUTC", scope = Invoice.class)
    public JAXBElement<XMLGregorianCalendar> createInvoiceUpdatedDateUTC(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_InvoiceUpdatedDateUTC_QNAME, XMLGregorianCalendar.class, Invoice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Items")
    public JAXBElement<ArrayOfItem> createItems(ArrayOfItem value) {
        return new JAXBElement<ArrayOfItem>(_Items_QNAME, ArrayOfItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Accounts")
    public JAXBElement<ArrayOfAccount> createAccounts(ArrayOfAccount value) {
        return new JAXBElement<ArrayOfAccount>(_Accounts_QNAME, ArrayOfAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Users")
    public JAXBElement<ArrayOfUser> createUsers(ArrayOfUser value) {
        return new JAXBElement<ArrayOfUser>(_Users_QNAME, ArrayOfUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfBankTransaction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BankTransactions")
    public JAXBElement<ArrayOfBankTransaction> createBankTransactions(ArrayOfBankTransaction value) {
        return new JAXBElement<ArrayOfBankTransaction>(_BankTransactions_QNAME, ArrayOfBankTransaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTrackingCategory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrackingCategories")
    public JAXBElement<ArrayOfTrackingCategory> createTrackingCategories(ArrayOfTrackingCategory value) {
        return new JAXBElement<ArrayOfTrackingCategory>(_TrackingCategories_QNAME, ArrayOfTrackingCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Response")
    public JAXBElement<ResponseType> createResponse(ResponseType value) {
        return new JAXBElement<ResponseType>(_Response_QNAME, ResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfEmployee }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Employees")
    public JAXBElement<ArrayOfEmployee> createEmployees(ArrayOfEmployee value) {
        return new JAXBElement<ArrayOfEmployee>(_Employees_QNAME, ArrayOfEmployee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfBrandingTheme }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrandingThemes")
    public JAXBElement<ArrayOfBrandingTheme> createBrandingThemes(ArrayOfBrandingTheme value) {
        return new JAXBElement<ArrayOfBrandingTheme>(_BrandingThemes_QNAME, ArrayOfBrandingTheme.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Setup")
    public JAXBElement<SetupType> createSetup(SetupType value) {
        return new JAXBElement<SetupType>(_Setup_QNAME, SetupType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTaxRate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TaxRates")
    public JAXBElement<ArrayOfTaxRate> createTaxRates(ArrayOfTaxRate value) {
        return new JAXBElement<ArrayOfTaxRate>(_TaxRates_QNAME, ArrayOfTaxRate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfAttachment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Attachments")
    public JAXBElement<ArrayOfAttachment> createAttachments(ArrayOfAttachment value) {
        return new JAXBElement<ArrayOfAttachment>(_Attachments_QNAME, ArrayOfAttachment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfManualJournal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Manualjournals")
    public JAXBElement<ArrayOfManualJournal> createManualjournals(ArrayOfManualJournal value) {
        return new JAXBElement<ArrayOfManualJournal>(_Manualjournals_QNAME, ArrayOfManualJournal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCurrency }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Currencies")
    public JAXBElement<ArrayOfCurrency> createCurrencies(ArrayOfCurrency value) {
        return new JAXBElement<ArrayOfCurrency>(_Currencies_QNAME, ArrayOfCurrency.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCreditNote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditNotes")
    public JAXBElement<ArrayOfCreditNote> createCreditNotes(ArrayOfCreditNote value) {
        return new JAXBElement<ArrayOfCreditNote>(_CreditNotes_QNAME, ArrayOfCreditNote.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfInvoice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Invoices")
    public JAXBElement<ArrayOfInvoice> createInvoices(ArrayOfInvoice value) {
        return new JAXBElement<ArrayOfInvoice>(_Invoices_QNAME, ArrayOfInvoice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfOrganisation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Organisations")
    public JAXBElement<ArrayOfOrganisation> createOrganisations(ArrayOfOrganisation value) {
        return new JAXBElement<ArrayOfOrganisation>(_Organisations_QNAME, ArrayOfOrganisation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Contacts")
    public JAXBElement<ArrayOfContact> createContacts(ArrayOfContact value) {
        return new JAXBElement<ArrayOfContact>(_Contacts_QNAME, ArrayOfContact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfJournal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Journals")
    public JAXBElement<ArrayOfJournal> createJournals(ArrayOfJournal value) {
        return new JAXBElement<ArrayOfJournal>(_Journals_QNAME, ArrayOfJournal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfExpenseClaim }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpenseClaims")
    public JAXBElement<ArrayOfExpenseClaim> createExpenseClaims(ArrayOfExpenseClaim value) {
        return new JAXBElement<ArrayOfExpenseClaim>(_ExpenseClaims_QNAME, ArrayOfExpenseClaim.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfLineItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineItems")
    public JAXBElement<ArrayOfLineItem> createLineItems(ArrayOfLineItem value) {
        return new JAXBElement<ArrayOfLineItem>(_LineItems_QNAME, ArrayOfLineItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfReceipt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Receipts")
    public JAXBElement<ArrayOfReceipt> createReceipts(ArrayOfReceipt value) {
        return new JAXBElement<ArrayOfReceipt>(_Receipts_QNAME, ArrayOfReceipt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdatedDateUTC", scope = Contact.class)
    public JAXBElement<XMLGregorianCalendar> createContactUpdatedDateUTC(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_InvoiceUpdatedDateUTC_QNAME, XMLGregorianCalendar.class, Contact.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FullyPaidOnDate", scope = CreditNote.class)
    public JAXBElement<XMLGregorianCalendar> createCreditNoteFullyPaidOnDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_InvoiceFullyPaidOnDate_QNAME, XMLGregorianCalendar.class, CreditNote.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubTotal", scope = CreditNote.class)
    public JAXBElement<BigDecimal> createCreditNoteSubTotal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CreditNoteSubTotal_QNAME, BigDecimal.class, CreditNote.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdatedDateUTC", scope = CreditNote.class)
    public JAXBElement<XMLGregorianCalendar> createCreditNoteUpdatedDateUTC(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_InvoiceUpdatedDateUTC_QNAME, XMLGregorianCalendar.class, CreditNote.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DueDate", scope = CreditNote.class)
    public JAXBElement<XMLGregorianCalendar> createCreditNoteDueDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreditNoteDueDate_QNAME, XMLGregorianCalendar.class, CreditNote.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalTax", scope = CreditNote.class)
    public JAXBElement<BigDecimal> createCreditNoteTotalTax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CreditNoteTotalTax_QNAME, BigDecimal.class, CreditNote.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
	@XmlElementDecl(namespace = "", name = "LineAmountTypes", scope = CreditNote.class)
    public JAXBElement<List<String>> createCreditNoteLineAmountTypes(List<String> value) {
        return new JAXBElement<List<String>>(_CreditNoteLineAmountTypes_QNAME, ((Class) List.class), CreditNote.class, ((List<String> ) value));
    }

}
