//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 04:46:40 PM EST 
//


package au.com.sixtree.mule.modules.xero.xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for organisationEntityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="organisationEntityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="PERSONAL"/>
 *     &lt;enumeration value="CHARITY"/>
 *     &lt;enumeration value="COMPANY"/>
 *     &lt;enumeration value="PARTNERSHIP"/>
 *     &lt;enumeration value="PERSON"/>
 *     &lt;enumeration value="SOLETRADER"/>
 *     &lt;enumeration value="TRUST"/>
 *     &lt;enumeration value="CLUBSOCIETY"/>
 *     &lt;enumeration value="PRACTICE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "organisationEntityType")
@XmlEnum
public enum OrganisationEntityType {

    PERSONAL,
    CHARITY,
    COMPANY,
    PARTNERSHIP,
    PERSON,
    SOLETRADER,
    TRUST,
    CLUBSOCIETY,
    PRACTICE;

    public String value() {
        return name();
    }

    public static OrganisationEntityType fromValue(String v) {
        return valueOf(v);
    }

}
